name: Tests

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: "Tests: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read
  checks: write # required by mikepenz/action-junit-report


jobs:

  gradle-check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    uses: ./.github/workflows/run_gradle_task.yml
    with:
      runs-on: ${{ matrix.os }}
      gradle-task: >-
        check -Pkxstsgen_enableTsCompileTests=true --stacktrace

  build-site:
    # verify that the site can be built, but don't deploy it
    uses: ./.github/workflows/run_gradle_task.yml
    with:
      runs-on: ubuntu-latest
      gradle-task: docusaurusBuild
