name: Publish Maven


on:
  workflow_dispatch:
  workflow_call:


concurrency:
  group: "Publish Maven: ${{ github.workflow }}"
  cancel-in-progress: false


permissions:
  contents: write
  packages: write
  checks: write


jobs:

  sonatype-release:
    permissions:
      contents: read
      packages: write
      checks: write
    uses: ./.github/workflows/run_gradle_task.yml
    secrets: inherit
    with:
      runs-on: macos-latest # only macOS supports building all Kotlin targets
      gradle-task: >-
        publishAllPublicationsToSonatypeReleaseRepository --stacktrace --no-configuration-cache --no-parallel
